EE/Prj_CursoAluno/src/main/java/managedbeans/AlunoManagedBean.java
package managedbeans;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import org.primefaces.event.RowEditEvent;

import modelos.Aluno;
import modelos.Curso;
import servico.Servico;

@ManagedBean(name="alunoManagedBean")
@RequestScoped
public class AlunoManagedBean {
	private Aluno aluno = new Aluno();
	private Curso curso;
	private Servico servico = new Servico();
	private List<Aluno> alunos = null;
	
	public void onRowEdit(RowEditEvent event) 
	{
        Aluno a = (Aluno) event.getObject();
        servico.upDateAluno(a);
		
    }
	
	public void salvar(){
		curso.addAluno(aluno);
		aluno.setCurso(curso);
		servico.saveAluno(aluno);
		
		aluno = new Aluno();
		curso = null;
		alunos = null;
	}
	
	public List <Curso> getCursos(){
		return servico.getCursos();
	}

	public Aluno getAluno() {
		return aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public void remove(Aluno aluno){
		alunos.remove(aluno);
		servico.removeAluno(aluno);;
	}
	
	public List<Aluno> getListaAlunos(){
		if(alunos == null){
			alunos = servico.getAlunos();
			
		}
		return alunos;
	}
	
	
}

EE/Prj_CursoAluno/src/main/java/managedbeans/CursoManagedBean.java
package managedbeans;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.RowEditEvent;

import modelos.Curso;
import servico.Servico;

@ManagedBean(name="cursoManagedBean")
@RequestScoped
public class CursoManagedBean {
	private Curso curso = new Curso();
	private Servico servico = new Servico();
	private List<Curso> cursos;
	
	public void onRowEdit(RowEditEvent event) 
	{
        Curso c = (Curso) event.getObject();
        servico.upDateCurso(c);
    }
	
	public void salvar(){
		servico.saveCurso(curso);
		curso = new Curso();
	}
	
	public List<Curso> getCursos(){
		if(cursos == null){
			cursos = servico.getCursos();
		}
		return cursos;
	}

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}
	
	public void remove(Curso curso){
		if(servico.removeCurso(curso)){
			cursos.remove(curso);
		}
		else{
			 FacesMessage msg = new FacesMessage("Impossível remover curso com alunos", "Sigla: " + curso.getSigla() + " Descricao:" + curso.getDescricao());
		     FacesContext.getCurrentInstance().addMessage(null, msg);
		}
	}
}

EE/Prj_CursoAluno/src/main/webapp/cadastrarAluno.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<meta charset="UTF-8" />
	
</h:head>

<h:body>

    <p:link value="Menu" outcome="menu"/>
	<h:form id="formAlunos">

		<p:panelGrid columns="2">
			
			<p:outputLabel value="Nome:" />
			<p:inputText value="#{alunoManagedBean.aluno.nome}" />

			<p:outputLabel value="Curso:" />
			<p:selectOneMenu value="#{alunoManagedBean.curso}"
				converter="converterCurso">
				<f:selectItem itemValue="" itemLabel="Selecione um curso" />
				<f:selectItems value="#{alunoManagedBean.cursos}" var="aux"
					itemValue="#{aux}" itemLabel="#{aux.descricao}" />
			</p:selectOneMenu>

			<p:outputLabel value="Faltas:" />
			<p:inputText value="#{alunoManagedBean.aluno.faltas}" />
			
			<p:outputLabel value="Nota 1:" />
			<p:inputText value="#{alunoManagedBean.aluno.nota1}" />
			
			<p:outputLabel value="Nota 2:" />
			<p:inputText value="#{alunoManagedBean.aluno.nota2}" />


		</p:panelGrid>
		<p:commandButton value="Salvar" action="#{alunoManagedBean.salvar}"
			update=":formAlunos, :formTableAlunos" />
	</h:form>

	<h:form id="formTableAlunos">
	
		<p:dataTable value="#{alunoManagedBean.listaAlunos}" var="alu"	editable="true" id="tableAlunos" >

            <p:ajax event="rowEdit" listener="#{alunoManagedBean.onRowEdit}" update=":formTableAlunos:tableAlunos" />  
			
			<p:column headerText="Registro">
				<h:outputText value="#{alu.registro}" />
			</p:column>

			<p:column headerText="Nome">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{alu.nome}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{alu.nome}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>


			<p:column headerText="Curso">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{alu.curso.descricao}" />
					</f:facet>
					<f:facet name="input">
						<p:selectOneMenu value="#{alu.curso}"
							converter="converterCurso" style="width:100%">
							<f:selectItem itemValue="" itemLabel="Selecione um curso" />
							<f:selectItems value="#{alunoManagedBean.cursos}"
								var="aux" itemValue="#{aux}" itemLabel="#{aux.descricao}" />
						</p:selectOneMenu>

					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column headerText="Faltas">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{alu.faltas}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{alu.faltas}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="Nota 1">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{alu.nota1}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText  value="#{alu.nota1}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="Nota 2">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{alu.nota2}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText id="modelInput" value="#{alu.nota2}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>
			
			<p:column headerText="Média">
				<h:outputText value="#{alu.calcMedia()}" />
			</p:column>

			<p:column style="width:70px" headerText="Opções">
					<p:rowEditor>

					</p:rowEditor>
					
					<p:commandLink id="remover" styleClass="ui-icon ui-icon-trash"
						style="text-align:center"
						actionListener="#{alunoManagedBean.remove(alu)}"
						update=":formTableAlunos" />
			</p:column>
		</p:dataTable>
	</h:form>
</h:body>
</html>

EE/Prj_CursoAluno/src/main/webapp/cadastrarCurso.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<meta charset="UTF-8" />
</h:head>
<h:body>

	<p:link value="Menu" outcome="menu" />
	<h:form id="formCurso">



		<p:panelGrid columns="2">
			<p:outputLabel value="Sigla:" />
			<p:inputText value="#{cursoManagedBean.curso.sigla}" />
			
			<p:outputLabel value="Descrição:" />
			<p:inputText value="#{cursoManagedBean.curso.descricao}" />
		</p:panelGrid>

		<p:commandButton value="Salvar" action="#{cursoManagedBean.salvar}"
			update=":formCurso, :formTableCursos" />
	</h:form>

	<h:form id="formTableCursos">

		<p:growl id="msgs" showDetail="true" />


		<p:dataTable value="#{cursoManagedBean.cursos}" var="cur"
			editable="true" id="tableCursos">

			<p:ajax event="rowEdit" listener="#{cursoManagedBean.onRowEdit}" />

			<p:column headerText="Código">
				<h:outputText value="#{cur.codigo}" />
			</p:column>

			<p:column headerText="Sigla">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{cur.sigla}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText id="modelInput" value="#{cur.sigla}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column headerText="Descricao">
				<p:cellEditor>
					<f:facet name="output">
						<p:outputLabel value="#{cur.descricao}" />
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{cur.descricao}"
							style="width:100%" />
					</f:facet>
				</p:cellEditor>
			</p:column>


			<p:column style="width:70px" headerText="Opções">
				<p:rowEditor />
				<p:commandLink id="remover" styleClass="ui-icon ui-icon-trash"
					style="text-align:center"
					actionListener="#{cursoManagedBean.remove(cur)}"
					update=":formTableCursos, :formTableCursos:msgs" />
			</p:column>

		</p:dataTable>
	</h:form>
</h:body>
</html>

EE/Prj_CursoAluno/src/main/webapp/menu.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<meta charset="UTF-8" />
</h:head>
<h:body>


	<p:outputLabel value="Menu" />
	<br />
	<p:link value="Cadastro Curso" outcome="cadastrarCurso" />
	<br />
	<p:link value="Cadastro Aluno" outcome="cadastrarAluno" />

</h:body>
</html>